### ISSUE TITLE
建议 加一个自动测试功能，有些接口可能无法解析了？定时跑一个报告出来，是否测试通过

### ISSUE THREAD

**Issue by chenGit1763113879QQ** [akfamily/akshare#3584]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yutyflynew1** [comment]
stock_zh_a_minute_df = ak.stock_zh_a_minute(symbol='sh600751', period='1', adjust="qfq")

raise SSLError(e, request=request)

SSLError: HTTPSConnectionPool(host='quotes.sina.cn', port=443): Max retries exceeded with url: /cn/api/jsonp_v2.php/=/CN_MarketDataService.getKLineData?symbol=sh600751&scale=1&ma=no&datalen=36580 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

**Comment by jindaxiang** [comment]
> stock_zh_a_minute

接口正常；

> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

good idea！
